# Generated by Django 5.1.4 on 2025-01-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='category',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
